### ISSUE TITLE
コミットメッセージテンプレートの作成

### ISSUE THREAD

**Issue by pss-aileen** [first-contributions-ja/first-contributions-ja.github.io#1]

**Comment by pss-aileen** [comment]
### kazzfrogさんの書かれているprefix

> chore: Create Next App
> fix: build時のエラーを修正

### 調べて出てきたprefix

> feat: A new feature
> fix: A bug fix
> docs: Documentation only changes
> style: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
> refactor: A code change that neither fixes a bug nor adds a feature
> perf: A code change that improves performance
> test: Adding missing tests
> chore: Changes to the build process or auxiliary tools and libraries such as documentation generation
> [Git Commit Guidelines | EU System](https://ec.europa.eu/component-library/v1.15.0/eu/docs/conventions/git/)

日本語訳

- feat：新機能
- fix : バグ修正
- docs : ドキュメントのみの変更
- style : コードの意味に影響を与えない変更 (空白、書式設定、セミコロンの欠落など)
- refactor: バグの修正も機能の追加も行わないコード変更
- perf : パフォーマンスを向上させるコード変更
- test : 不足しているテストを追加します
- chore : ビルド プロセス、またはドキュメント生成などの補助ツールやライブラリへの変更

**Comment by pss-aileen** [comment]
## プルリクエストテンプレートとは

> ”本番適用するソースコードは必ずレビューする” というルールを決めたとしても「忙しくてレビューできない」「レビューしたいけど、どこが変わったか見つけるのが面倒」などの意見が多く、レビューをしなくなっていきます。
> 
> コードレビューする文化を組織に根付かせることは、とても難しいです。しかし、プルリクエストを使うことで組織にコードレビューする文化を根付かせることができます。
> [プルリクエストとは？｜サル先生のGit入門【プロジェクト管理ツールBacklog】](https://backlog.com/ja/git-tutorial/pull-request/01/)

> **プルリクエストとは簡単に言うと、開発者のローカルリポジトリでの変更を他の開発者に通知する機能です。プルリクエストは次のような機能を提供します。**
> - 機能追加や改修など、作業内容をレビュー・マージ担当者やその他関係者に通知します。
> - ソースコードの変更箇所をわかりやすく表示します。
> - ソースコードに関するコミュニケーションの場を提供します。

- テンプレート例  ref: [GitHub pull request template](https://axolo.co/blog/p/part-3-github-pull-request-template)
  - チェックリストなどを含めるパターン
  - 詳細説明を書くパターン

<img src="https://github.com/first-contributions-ja/first-contributions-ja/assets/140990100/523e2f2d-c448-4984-b84d-ab82f7b90aa7" width="400">

- [リポジトリ用のプルリクエストテンプレートの作成 - GitHub Docs](https://docs.github.com/ja/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)
- [GithubでPull Request テンプレートを使用するには？ #Git - Qiita](https://qiita.com/atsutama/items/03753925762fd094ec9c#:~:text=Pull%20Request%E3%83%86%E3%83%B3%E3%83%97%E3%83%AC%E3%83%BC%E3%83%88%E3%81%AF%E3%80%81%E3%83%97%E3%83%AD%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88,%E3%83%95%E3%82%A3%E3%83%BC%E3%83%89%E3%83%90%E3%83%83%E3%82%AF%E3%82%92%E6%8F%90%E4%BE%9B%E3%81%A7%E3%81%8D%E3%81%BE%E3%81%99%E3%80%82)

## イシューテンプレートとは

**issueを投稿する時のテンプレート**

![スクリーンショット 2024-03-12 7 48 15](https://github.com/first-contributions-ja/first-contributions-ja/assets/140990100/f87586e1-29dc-4da4-a7ef-ecb799978cb3)

- [リポジトリ用に Issue テンプレートを設定する - GitHub Docs](https://docs.github.com/ja/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)
- [他の人が見ても分かるIssueを書くために意識していること #GitHub - Qiita](https://qiita.com/shunbaba/items/23c26d1800d879c33043)
- ★参考になる気がする [オレオレ GitHub Issue テンプレートを晒す - ほとラボ](https://hoto17296.hatenablog.com/entry/github_template)

**Comment by pss-aileen** [comment]
## イシューテンプレートとは

**issueを投稿する時のテンプレート**

![スクリーンショット 2024-03-12 7 48 15](https://github.com/first-contributions-ja/first-contributions-ja/assets/140990100/f87586e1-29dc-4da4-a7ef-ecb799978cb3)

- [リポジトリ用に Issue テンプレートを設定する - GitHub Docs](https://docs.github.com/ja/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)
- [他の人が見ても分かるIssueを書くために意識していること #GitHub - Qiita](https://qiita.com/shunbaba/items/23c26d1800d879c33043)
- ★参考になる気がする [オレオレ GitHub Issue テンプレートを晒す - ほとラボ](https://hoto17296.hatenablog.com/entry/github_template)

**Comment by kagomen** [comment]
コミットメッセージにIssueを書くと良いみたいです？

<img width="790" alt="スクリーンショット 2024-03-12 21 09 07" src="https://github.com/first-contributions-ja/first-contributions-ja/assets/154225199/0167174e-544d-4f04-a79b-91bd158739bc">

[未経験がWeb系転職成功したいならgithubでissue管理して開発しよう](https://qiita.com/fukubaka0825/items/c7710b4e87d478c8ba3b)

**Comment by pss-aileen** [comment]
![スクリーンショット 2024-03-12 20 34 21](https://github.com/first-contributions-ja/first-contributions-ja/assets/140990100/9132d94b-ad26-4714-8f5a-d21348b7e3ee)

ですね！
基本シンプルですが、こんな形で書けたらいいのかなぁ〜と思っています！

**Comment by kagomen** [comment]
わかりやすい！

**Comment by pss-aileen** [comment]
#6 
とりあえずざっくりしたものは決まったので一旦Close
