### ISSUE TITLE
マイルストーン or Projects の作成

### ISSUE THREAD

**Issue by pss-aileen** [first-contributions-ja/first-contributions-ja.github.io#10]
- [x] Projectsの作成
  - 塊ごとにProjectsを作って管理、終わったらクローズして新しいProjects作れたらいい気がしている 
- [ ] マイルストーンを作る
  - 作らなくていいような気もしてきた、保留 

---

進捗・優先度の確認に良さそう

- [開発者のスケジュール管理に超便利、GitHub Issues、Label、Milestone、Projects使いこなし術：こっそり始めるGit／GitHub超入門（12）（4/4 ページ） - ＠IT](https://atmarkit.itmedia.co.jp/ait/articles/1704/28/news032_4.html)
- [Issue とプルリクエストのマイルストーンの作成と削除 - GitHub Docs](https://docs.github.com/ja/issues/using-labels-and-milestones-to-track-work/creating-and-editing-milestones-for-issues-and-pull-requests)

**Comment by kazzyfrog** [comment]
>塊ごとにProjectsを作って管理、終わったらクローズして新しいProjects作れたらいい気がしている

Projects分けるのいいですね！自分もこれに賛成です！

マイルストーンは確かに先でも良さそうです！
その場合一旦このイシューはクローズしちゃっていいかも👍
