### ISSUE TITLE
マークダウンファイルの英数字前後に半角スペースが入る問題についてルール制定、Prettier設定をする

### ISSUE THREAD

**Issue by pss-aileen** [first-contributions-ja/first-contributions-ja.github.io#103]
## 現在の状態

- Prettierのフォーマット時に、数字や英語の文字の前後に自動で半角スペースが入ってしまう
https://github.com/first-contributions-ja/first-contributions-ja.github.io/pull/89#discussion_r1536760698

## 理想の状態

- マークダウン、というよりドキュメントの書き方を制定する
  - 英数字の前後に半角空白を入れるか、なるべく正式名称を使うなど（それぐらいしかないかもですが...）
- 上記の設定をもとに、Prettier を適切な状態に設定する

## タスク一覧

- [ ] Prettierの対象からmarkdownを除外する ignoreファイル

## その他

- ドキュメントの書き方を制定→英数字前後に半角スペース入れるか入れないか

- markdownを整形すると見た目で不具合が出たりするような気もするので、整形対象からそもそもはずした方が良いと考えている

**Comment by kagomen** [comment]
自分も元々Prettierのプラグインを入れてたのですが、マークダウンを書くのに不便だったので無効にしてました。
マークダウンファィルだけPrettierを効かなくするのは、選択肢としてどう思いますか❓

AileenさんがPrettierのことについて書かれてるDiscussion見てたら、ignoreファイルでフォーマットを無効にするのもありなのかなーと思ったりしました！

<img width="728" alt="スクリーンショット 2024-03-26 21 42 26" src="https://github.com/first-contributions-ja/first-contributions-ja.github.io/assets/154225199/90853250-f1d6-41b3-86a0-67de29555446">

**Comment by pss-aileen** [comment]
色々試してて、Prettierをマークダウンに適応させない、ignoreする方向で良いかなと私も思いました！
なのでこちら、ignoreでいきます！いきましょう！

あと、英数字の前後の半角空白を入れるか入れないかについては、
個人的にはいっていたほうが読みやすいな〜と思うのであけたままで良いかなと思っています。

**Comment by kagomen** [comment]
了解です！
半角空白の件も承知しました！

https://github.com/first-contributions-ja/first-contributions-ja.github.io/discussions/52#discussioncomment-8939688

共有事項に記入しておきましたので、必要あれば編集お願いします🙏
