### ISSUE TITLE
ドックフーディングを実施し、不明点・修正点を洗い出す

### ISSUE THREAD

**Issue by pss-aileen** [first-contributions-ja/first-contributions-ja.github.io#104]
## 概要

- #97 
- リリース前に自分たちでユーザーと同じ流れでテストを行う

## タスク一覧

- [x] できる人だけで良いのでドックフーディングを実施する
- [ ] それぞれ感想・不明点などを洗い出す

## その他

- 不明点や修正すべき点があればIssue立てして改善する

**Comment by kazzyfrog** [comment]
全員実施したので、このissueはクローズされます！

ドッグフーディングして、発見した問題やアイデアは、
discussions #150 にて話し合われ、issueに追加されます！
