### ISSUE TITLE
Contributors.jsonの内容変更

### ISSUE THREAD

**Issue by pss-aileen** [first-contributions-ja/first-contributions-ja.github.io#112]
## 理想の状態

```json
{
  "name": "あなたのハンドルネーム",
  "github": "あなたのGitHubアカウントのURL",
  "favoriteStack": "あなたの好きなプログラミング言語・技術スタック",
  "favoriteColor": "あなたの好きなカラーコード",
  "favoriteEmoji": "あなたの好きな絵文字",
},
```

## タスク一覧

- [ ]

**Comment by pss-aileen** [comment]
@kagomen さんのツイッターにあったOctcatの画像使えたらよさそう...！
と思うが、利用規約等確認したほうがいいかも
これもあれば賑やかで楽しそう
ただ、作るのは大変そうだけど、でもランダムあるからいいか

https://github.blog/jp/2018-10-17-myoctocat/
https://myoctocat.com/
https://myoctocat.com/terms/

![スクリーンショット 2024-03-25 2 09 55](https://github.com/first-contributions-ja/first-contributions-ja.github.io/assets/140990100/4911cfb5-17e8-4c3c-9ba3-0f536abad635)

**Comment by pss-aileen** [comment]
ただ、リポジトリに上限があるので画像ないほうがよい...？
https://support-ja.backlog.com/hc/ja/articles/360036149853-Git%E3%83%AA%E3%83%9D%E3%82%B8%E3%83%88%E3%83%AA%E3%81%AE%E3%82%B5%E3%82%A4%E3%82%BA%E3%81%AB%E4%B8%8A%E9%99%90%E3%81%AF%E3%81%82%E3%82%8A%E3%81%BE%E3%81%99%E3%81%8B

最悪増えすぎたら今のをコピーしたリポジトリを作ればいいjか

> 10GBは10,000,000KBに相当します。画像のサイズが500〜800KBの場合、その範囲内で平均して650KBと見積もると、10,000,000KB ÷ 650KB = 約15,384枚の画像を保存できます。
> ただし、実際にはファイルシステムのオーバーヘッドや他の要因により、少し少なくなる可能性があります。

**Comment by kazzyfrog** [comment]
V1リリースと、ドッグフーディングまで持っていくため、
いったん仮決定している、理想の状態に変更しますね！

以下に関しては、ディスカッションで、思いついたアイデアを投稿・発散させるスレッドを作ってもいいかもです！
主にV2の内容：
- コンセプト・ストーリー
- 個別ページやトップページの表示
- Contributors.jsonや画像など、入力してもらう内容
