### ISSUE TITLE
リリースブログを作成する

### ISSUE THREAD

**Issue by pss-aileen** [first-contributions-ja/first-contributions-ja.github.io#114]
## 概要
- First Contributions JA としてのブログ、リリースノート？を立ち上げる

> - 記録をとっておきたい
>   - 企業ブログにバージョン1リリースしました、前回まではこうだった、こういう変化があったよ
>   - 広報？的な、ドットインストール的な変更などをお知らせしたい
>   - ブログみたいなものを作りたいな！
> https://github.com/first-contributions-ja/first-contributions-ja.github.io/discussions/76#discussioncomment-8892670

## タスク一覧

- [ ] 書く媒体を探す
- [ ] バージョン2をローンチする際に投稿する

**Comment by kagomen** [comment]
選択肢としては

- ブログ（ニュース）ページを作り、リポジトリ内で記事管理をする
- ブログサービスを利用する

の2つかな？

### ZennのPublicationやQiitaのOrganizationは？

- PublicationやOrganizationはプロジェクト単位ではなくチーム（会社など）として開設してるのでちょっと違うと思う
  - なのでもしPublicationやOrganizationを作成するとしたら、チームを作りたいと思った
    - このプロジェクトにとどまらず、他にもプロジェクトを作るということであれば、チームを作るのも良いと思った（気が早いですか……？）
  - チームを作るならチームのサイトを作って、そこにPublicationやOrganizationのリンクを貼るのが適切かなと思った

### 表記はブログかニュースか
- 個人的には広報のイメージなのでニュース！って感じだったけど、React、Astro、Svelte、Angularの公式サイトを見ると全部Blogだった（VueはNewsの下にBlogがあった(?)）。うーん

**Comment by kagomen** [comment]
ドットインストールを見てみたら、
「運営からのお知らせ」で https://dotinstall.com/news に飛ばされて、お知らせのタイトルをクリックしたらNoteの記事に飛ぶ仕組みになってた
なるほど…… すごいなあ

<img width="1127" alt="スクリーンショット 2024-03-25 14 35 09" src="https://github.com/first-contributions-ja/first-contributions-ja.github.io/assets/154225199/c0a19248-39d3-4750-8264-4186cb1915df">

**Comment by kagomen** [comment]
自分だけのプロジェクトだったら、ブログでもニュースでもなく「広報室便り」とかにする笑

**Comment by kagomen** [comment]
## 結局3択か

### 1. ブログサービスにそのまま飛ばす
 - 一番楽、だけどリンク名に迷う。
   - (Noteのロゴ)Note」だとNoteで何書いてるのかわからない
   - 「Blog」でいきなりNoteに飛ばされるのってどうなんだろう
 
### 2. ドットインストール式
- APIでタイトル・日付などを取得してきてタイトル表示だけリポジトリ内で行う
  - APIの勉強になるかも？

### 3. 記事をリポジトリ内で管理する
- 一番安心だけど一番面倒
  - マークダウンで記事を書くとして、どのように反映させるか、とか、シンタックスハイライトのライブラリの導入とか、色々やることありそう
  - 勉強になるとは思う
  - たかが広報ブログなのに？という感じはする

**Comment by kagomen** [comment]
リリースノートを取り入れた結果、現在の自分の気持ちとしては、リリースブログの実装は必要ない気がしているのですが、どう思いますか？
バージョンごとの記録などは、リリースノートに書けば良いかなーと……。

**Comment by kagomen** [comment]
どっちでも良いですよーという感じだったら、一旦実装予定を無しにして、イシューをクローズさせようと思います！

**Comment by kazzyfrog** [comment]
> 一旦実装予定を無しにして、イシューをクローズ

確かにそうですね！良いと思います👍
