### ISSUE TITLE
カード・個別ページのデザイン・実装の方針を決める

### ISSUE THREAD

**Issue by pss-aileen** [first-contributions-ja/first-contributions-ja.github.io#115]
## タスク一覧

- [ ] ざっくり実装デザイン・動き（絵文字）の作成

**Comment by kazzyfrog** [comment]
バージョン２までの流れとして、以下のような方針で一旦決まったため、
この親タスクは、クローズされます！

（もしかしたら、またオープンされます）

- バージョン２の仕様決め：
  - [ ] コンセプト決め： #119
  - [ ]   - デザイン案だし： figma＋ディスカッション？にて行う
  - [ ]   - デザインカンプ用意： #116

- バージョン２の実装！
  - [ ] 個別ページ #118
  - [ ] トップページ（カード？） #117
