### ISSUE TITLE
v2デザインカンプの作成

### ISSUE THREAD

**Issue by pss-aileen** [first-contributions-ja/first-contributions-ja.github.io#116]
## 概要

各々でv2デザインカンプの作成をする
一旦、期限は4/21(日)のMTGまで（途中でもOK！）

## タスク一覧

- [ ] 絵文字を使ってPOPな方向で以下をデザインし直す
  - TOPページ
    - ヘッダーコンポーネント
    - フッターコンポーネント
    - ヒーローセクション
    - アバウトセクション
  - 生成されるLGTM画像（OGのサイズなら、1200px×630px）
  - その他、ホバー時？や個別ページ？の表示など、アイデアがあれば💡

## その他

- カンプ作成後、案を持ち寄って話し合いでデザインをつめていく
- デザイン決定後、一人がデザインカンプを作成し、それをもとにコーディングを開始する

**Comment by kagomen** [comment]
#173 で完了！
技術などの調査後に、必要であれば最終的なデザイン案を作成する
