### ISSUE TITLE
リポジトリのコンセプト・ストーリー性の設定・記述

### ISSUE THREAD

**Issue by pss-aileen** [first-contributions-ja/first-contributions-ja.github.io#119]
## 概要

> - 絵文字と色のストーリー
> - POP，激しい、レインボー、ごちゃごちゃ
> - POPは楽しく取り組めたらいいな
> - 激しい：色々なものがあっていい、おもしろい
> - 自分の色
> https://github.com/first-contributions-ja/first-contributions-ja.github.io/discussions/76#discussioncomment-8892381

- 自分の個性をアピール
- 楽しむ

## タスク一覧

- [ ] ストーリーを文章化
- [ ] README.mdなどにコンセプトを記述

**Comment by kagomen** [comment]
一応自分なりの理解をまとめてみました！
Discussionsにも書いてPinしておくので、何か追記事項があればそちらにお願いします！

---


## プロジェクトの目的
- 共同プロジェクト自体を（楽しく）体験する
- 学んだ技術を使う！学習の実践であり、成果物作り！
- とはいえ、それが誰かの役に立ったりして実際に使ってもらえるなら、それに越したことはない。なので、負荷がかかりすぎない範囲で、ペルソナの設定やユーザー体験も考えよう！
- 参照: [Figma](https://www.figma.com/file/xTVaHLu2OeeIBS8nGeDAvC/%E8%80%83%E3%81%88%E3%81%A6%E3%81%84%E3%82%8B%E3%81%93%E3%81%A8%E3%81%AE%E3%81%BE%E3%81%A8%E3%82%81?type=whiteboard&node-id=21-149&t=U87dwKfpryYub03d-0)

## プロジェクトのコンセプト
- OSSプロジェクトへのコントリビュートを完全日本語で体験できるチュートリアル
- 参照: https://github.com/first-contributions-ja/first-contributions-ja.github.io/discussions/122#discussioncomment-8976043

## プロジェクトの工夫（サイドコンセプト）
- コードレビューで使用できる、LGTM画像の生成（あくまでおまけ的な位置付け）
- 生成された画像をDLするページを生成 => ツイッターでシェアしてもらう => OGP画像が表示される

**Comment by kagomen** [comment]
そんなに目につくところにある必要もないかなと思ったので、DiscussionsではなくWikiに新しいページを作りました！
[このプロジェクトの目的やコンセプトについて - Wiki](https://github.com/first-contributions-ja/first-contributions-ja.github.io/wiki/%E3%81%93%E3%81%AE%E3%83%97%E3%83%AD%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E3%81%AE%E7%9B%AE%E7%9A%84%E3%82%84%E3%82%B3%E3%83%B3%E3%82%BB%E3%83%97%E3%83%88%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6)
