### ISSUE TITLE
アバウトセクションのリスト部分のリファクタリング

### ISSUE THREAD

**Issue by kagomen** [first-contributions-ja/first-contributions-ja.github.io#144]
## 現在の状態
リスト部分がベタ書きで、スタイルを変更する際に大変
アバウトセクションはバージョン2でも使い回しそうなので、リファクタリングする価値があると思った

## 理想の状態
mapでループさせるか、コンポーネント化する

## タスク一覧

- [ ] mapでループさせるか、コンポーネント化する

## その他

- こちらが参考になりそう！
  - https://tailwindcss.com/docs/reusing-styles#loops

**Comment by kagomen** [comment]
@kazzyfrog 

> リスト部分がベタ書きで、スタイルを変更する際に大変
アバウトセクションはバージョン2でも使い回しそうなので、リファクタリングする価値があると思った

ということでリファクタの検討をしていましたが、本日のMTG #173 で、アバウトセクションの内容が大幅に変更されそうなので、こちらは一旦このままでも良いかも、と思いました！
良ければクローズしようかなと思いますが、どう思いますか？

**Comment by kazzyfrog** [comment]
確かに、クロースで良いと思います！
v2のアバウトセクションの実装の際に、コンポーネントで分割できそうならする！って感じで良さそうですね👍
