### ISSUE TITLE
CONTRIBUTING.mdのprefixの使い方を更新

### ISSUE THREAD

**Issue by kagomen** [first-contributions-ja/first-contributions-ja.github.io#171]
## 現在の状態
> prefix に対応した絵文字
✨ feat: 新機能追加関連
📚 docs: ドキュメントの追加・修正・削除
🐛 fix: 機能やバグに関する修正
🎨 style: スタイル関連
🔧 chore: 雑事、カテゴライズする必要のないもの
その他は必要に応じて適宜追加

## 理想の状態
タスク一覧を参照

## タスク一覧

- [x] refactorを追加
- [x] prefixの定義を現在のラベルの説明に合わせる

## その他

ついでに、コミットメッセージとブランチ名のイシュー番号が前にあったり後ろにあったりするのをできれば統一したい

現在の状態: 
```
- コミットメッセージ
  - 📚 docs: README.md 日本語訳追加 #12
- ブランチ名
  - docs/#01-create-documents
```

個人的にはブランチ名を
```
docs/create-documents-#01
```

としたら良いんじゃないかなあと思うのですが、どうですか？
というか、そもそもブランチ名って人が見たり、記録に残ったりするもんなんでしょうか？
（自分はみなさんのブランチ名を気にしたことはない……！）

**Comment by kazzyfrog** [comment]
> `docs/create-documents-#01`
としたら良いんじゃないかなあと思うのですが、どうですか？

自分もあまり気にしていませんでしたが、その形で統一しても良いと思います！👍

>というか、そもそもブランチ名って人が見たり、記録に残ったりするもんなんでしょうか？
（自分はみなさんのブランチ名を気にしたことはない……！）

一応、下記のように記録されて、見れますよ！
<img width="894" alt="スクリーンショット 2024-04-07 16 28 41" src="https://github.com/first-contributions-ja/first-contributions-ja.github.io/assets/70629747/35483fe3-494c-440c-ae0b-77240ace737f">
