### ISSUE TITLE
初期のLGTM画像を用意する

### ISSUE THREAD

**Issue by kazzyfrog** [first-contributions-ja/first-contributions-ja.github.io#186]
## 概要
最新のv2の仕様では、複数のLGTM画像（テーマ）を生成できるようにする予定です。
なので、初期の状態で、複数のLGTM画像を用意しておきます！
3, 4とか？

## タスク一覧

- [ ] LGTM画像の追加

**Comment by kazzyfrog** [comment]
これは1人が、１〜２個とか、デザインを用意して、
指定のディレクトリにHTML、CSSで作成する感じでいいのかも！

**Comment by kagomen** [comment]
こちらの実装方法がよくわかってないのですが、JSXとTailwindで見た目を作る感じですか？👀

**Comment by kazzyfrog** [comment]
そうです！
下記のサイトのように、tailwindでも、インラインスタイルでも、実装できる感じです！
https://og-playground.vercel.app

完成系としては、上記のサイトの左上のタブで切り替えているのを、画像のカードで切り替えられるようにするイメージです！
（デザインカンプだと、右側のサイドバー）

**Comment by kazzyfrog** [comment]
個別ページは一旦保留となったので、このイシューはクローズされます。
