### ISSUE TITLE
チュートリアルの内容を紹介する、About セクションの実装

### ISSUE THREAD

**Issue by kazzyfrog** [first-contributions-ja/first-contributions-ja.github.io#196]
## 概要
仕様が更新されたので、それに合わせてTOPページに、About セクション（チュートリアルの内容の紹介）を追加します。

## タスク一覧

- [x] 画像は、[こちら](https://carbon.now.sh)から、Contributors.jsonのデータの画像を作成し、表示する
- [x] PC、スマホ版の実装

## その他

figmaの、デザインカンプを参考に、
細かい文章の表現などは適宜変更して記載する！

**Comment by pss-aileen** [comment]
### Contributors.jsonの内容

```json
{
"name": "あなたのハンドルネーム",
"github": "あなたのGitHubアカウントのURL",
"favoriteColor": "あなたの好きなカラーコード",
"favoriteEmoji": "あなたの好きな絵文字"
}
```

![スクリーンショット 2024-05-24 23 50 41](https://github.com/first-contributions-ja/first-contributions-ja.github.io/assets/140990100/72f50006-0f07-4f20-97f6-9dc571fbd1b6)
