### ISSUE TITLE
イシューテンプレートの作成

### ISSUE THREAD

**Issue by pss-aileen** [first-contributions-ja/first-contributions-ja.github.io#2]
## イシューテンプレートとは

**issueを投稿する時のテンプレート**

![スクリーンショット 2024-03-12 7 48 15](https://github.com/first-contributions-ja/first-contributions-ja/assets/140990100/f87586e1-29dc-4da4-a7ef-ecb799978cb3)

- [リポジトリ用に Issue テンプレートを設定する - GitHub Docs](https://docs.github.com/ja/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)
- [他の人が見ても分かるIssueを書くために意識していること #GitHub - Qiita](https://qiita.com/shunbaba/items/23c26d1800d879c33043)
- ★参考になる気がする [オレオレ GitHub Issue テンプレートを晒す - ほとラボ](https://hoto17296.hatenablog.com/entry/github_template)

---

## テンプレート例

```markdown
調査中
```

#### ref
- [GitHubのissue、こう書かれているとめちゃくちゃ嬉しい。良いissueの書き方とは｜Koushi Kagawa](https://note.com/koushikagawa/n/n500e2f4d4019)
- [他の人が見ても分かるIssueを書くために意識していること #GitHub - Qiita](https://qiita.com/shunbaba/items/23c26d1800d879c33043)
- [【github】issueを複数テンプレート化してissueを整理しよう！ | 2055年からきたごんじっち](https://gonjitti.com/blog/2019-08-25-github-template/)

**Comment by kagomen** [comment]
@kazzyfrog 

テンプレートの設定は@kazzyfrogさんにお任せして良いのでしょうか？

というのも、練習用の個人のプロジェクトでGitHub(Web)からイシューテンプレートを設定してみたのですが、以下の画像のように、設定内容が記述されたファイルがリポジトリの.githubディレクトリに作成され、テンプレートが設定されているようでした。
<img width="649" alt="スクリーンショット 2024-03-13 15 03 30" src="https://github.com/first-contributions-ja/first-contributions-ja.github.io/assets/154225199/7624511f-588b-4440-9e62-849436e4d1af">

ただ、[first-contributions-ja.github.io](https://github.com/first-contributions-ja/first-contributions-ja.github.io)のプロジェクトでは管理者権限の制約のため？、テンプレートの設定が自分でできなかったので、テンプレートの提案のみこちらでして、設定に関しては@kazzyfrogさんにお任せ、という流れでよろしいでしょうか？
それとも上記のようにこちらで.githubディレクトリを作成して、そこにテンプレートファイルをpushした方が良いですか？（管理者権限がある以上、それで設定できるのかわかりませんが……。）

**Comment by kazzyfrog** [comment]
> テンプレートの提案のみこちらでして、設定に関しては@kazzyfrogさんにお任せ、という流れでよろしいでしょうか？

OKです！

もしくは、既に.githubリポジトリがあるので、そこに手動でISSUE_TEMPLATEディレクトリを作成して、その中にテンプレートのファイルを配置しても、問題なくテンプレとして使えるようになると思います：
https://docs.github.com/ja/communities/using-templates-to-encourage-useful-issues-and-pull-requests/manually-creating-a-single-issue-template-for-your-repository

どちらでも大丈夫です👍

**Comment by kagomen** [comment]
了解です。
そしたらプルリクの経験をつみたいので、

>既に.githubリポジトリがあるので、そこに手動でISSUE_TEMPLATEディレクトリを作成して、その中にテンプレートのファイルを配置しても、問題なくテンプレとして使えるようになると思います

こちらに挑戦してみようと思います・・・！

**Comment by kazzyfrog** [comment]
ファイトです！🔥

もし、作業の途中にディスカッションを開始したい場合は、[Draft Pull Request](https://github.blog/jp/2019-02-19-introducing-draft-pull-requests/)を出すこともできます！

これはまだマージして欲しくないけど、作ったコードをとりあえず見てほしい時や、コードの実装方針についてディスカッションをしたい時に、便利です！
実際にタスクに着手していることを、周りに伝えるのにも役立ちますよ！

**Comment by pss-aileen** [comment]
> もし、作業の途中にディスカッションを開始したい場合は、[Draft Pull Request](https://github.blog/jp/2019-02-19-introducing-draft-pull-requests/)を出すこともできます！

こういうのないのかなぁ〜〜と思ってました！良さげですね...！！

**Comment by kagomen** [comment]
そんな機能が……！
早速使います！ありがとうございます🙏🌟

**Comment by kagomen** [comment]
@kazzyfrog 
ありがとうございます！🙏
参考にします！

**Comment by kazzyfrog** [comment]
> テキスト形式の方が自由度が高い

自分も同じ理由で、テキスト形式の方に１票いれます！

**Comment by pss-aileen** [comment]
私も同じなのでテキスト形式に1票で！

**Comment by kagomen** [comment]
わかりました！
そしたらテキスト形式のテンプレートを作成します！
