### ISSUE TITLE
Noto Emoji が表示されない問題を解決する

### ISSUE THREAD

**Issue by pss-aileen** [first-contributions-ja/first-contributions-ja.github.io#208]
## 現在の状態
- ブラウザ、デバイスによってヒーローエリアの絵文字が表示されない

## 理想の状態
- PC、iPhone（確認できる範囲）
- Chrome、Safari
- 上記で絵文字が表示されて、アニメーションがされている状態。

## タスク一覧

- [ ] #202 を参考に、絵文字の問題を修正する

## その他

- https://github.com/first-contributions-ja/first-contributions-ja.github.io/discussions/200#discussioncomment-9560432
- #202 
- 開発のときに、スマホでもきちんと確認すること

**Comment by kazzyfrog** [comment]
もしよかったら、こちらサクッとやってしまっても良いでしょうか？
（多分、 #202  の通りで解決するかと思われます！）

**Comment by kazzyfrog** [comment]
そしたら、まとめてできたら、 #200 内にある、「直したい不具合」にもチャレンジしてみますね！
無理そうなら、別で切り出します！！
