### ISSUE TITLE
チュートリアルにパッケージインストールの手順を追加する

### ISSUE THREAD

**Issue by pss-aileen** [first-contributions-ja/first-contributions-ja.github.io#273]
## 現在の状態
- `npm install` として、プレビューしたり、フォーマットしたりする流れがない
- push やマージする際に GitHub Actions でフォーマットをさせると面倒なことになったり、仕組み上難しいことがある #261 

## 理想の状態
- チュートリアルの内容にパッケージをインストールしてもらう流れを追加する

## タスク一覧

- [x] パッケージのインストールを「さらなるステップ」として組み込むか、Step n として追加するかを決める
- [ ] チュートリアルに以下の内容を入れ込む
  - [x] `npm install` でパッケージをインストールする方法
  - [ ] `npm install` ができない場合のガイド（他サイトへのリンクでも可）
  - [ ] `npm run dev` でプレビューして確認する方法
  - [ ] パッケージをインストールすることによって、コミット時に husky が動くこと
  - [ ] husky で ESLint、Prettier が動くこと
  - [ ] 必要であれば画像を追加する
  - [ ] その他あれば、こちらに追加

### 相談

タスク一覧にも書きましたが、以下についてご意見が欲しいです。

- 相談: パッケージインストールの流れは、さらなるステップ or Step n として追加するのではどちらが良いと思いますか？
- 私の意見: 「さらなるステップ」が良いと思う
- 理由: npm installからの流れは人によって難しいかもしれないから

**Comment by kazzyfrog** [comment]
issue 化ありがとうございます👍

個人的には、
Step2 or 3 あたりで、「npm install」をしてもらうのが良いかなと思いました！
（全然しっくりはきてないというか、悩んでいる感じですが。。！）

理由としては、２つです！

1.
現状、「さらなるステップ」は、
任意的な段落かと思っているので、実装されない可能性があるかも。

2.
絶対にして欲しいのは、「npm install」だけなので、
その後の流れ（previewやhusky,,）は、閉会式のアコーディオン内にて、説明するのでも良いかなと、少し思ってます！

→ただ、これでも、
ごちゃごちゃしてしまいそうな気も、しているんですよね。。🧐

**Comment by pss-aileen** [comment]
すみません、頭がこんがらがっていたのですが
npm install をすれば、huskyが走るようになるので、フォーマットの問題はクリアしますね。
npm run dev と混同していました。

> Step2 or 3 あたりで、「npm install」をしてもらうのが良いかなと思いました！

確かに、そうですね！
Step2かStep3あたりにあるのが良い気がしてきました！

npm installができない、トラブル発生の方は飛ばすか、別の参考になりそうなサイトを貼り付けてみてもらうかして...
ここで問題がおこらなければそのままスムーズにことは進むのではないかな...と思うので、Step2、3あたりに入れるべきだと思いました！

> その後の流れ（previewやhusky,,）は、開閉式のアコーディオン内にて、説明するのでも良いかなと、少し思ってます！

このあたりもまさにそうですね！
賛成です！

**Comment by kazzyfrog** [comment]
ですね！

問題なければ、　このイシューもらいますよ！
とりあえず、上記の通り変更して近日中にPR出してみますー👍

**Comment by pss-aileen** [comment]
> 問題なければ、　このイシューもらいますよ！
> とりあえず、上記の通り変更して近日中にPR出してみますー👍

すみません、お願いしても良いでしょうか...！
ありがとうございます！

よろしくお願いいたします🙇
