### ISSUE TITLE
[docs]Translate README into English.

### ISSUE THREAD

**Issue by kazzyfrog** [first-contributions-ja/first-contributions-ja.github.io#290]
## Overview

The README is currently written in Japanese.

In order to connect with more OSS developers,
I see a lot of value in translating the documentation into English.

## Task list

- [x] create `docs/README_EN.md`
- [x] Translate the content of the README into English.

## Others

The README file contains a large amount of text.
Therefore, some sections can be cut out as separate issues.

---

If anyone would like to challenge this Issue, please add a comment!

Thank you for your interest in this issue 🚀.

**Comment by RashmitTopG** [comment]
Can you assign me this

**Comment by RashmitTopG** [comment]
Translated the Readme.md into english and created a new docs/README_EN.md

**Comment by kazzyfrog** [comment]
Thanks for your contribution 🥳
