### ISSUE TITLE
[docs]In the `docs/README_EN.md`, the X-share button is not displayed correctly.

### ISSUE THREAD

**Issue by kazzyfrog** [first-contributions-ja/first-contributions-ja.github.io#293]
## Overview

In the README, the X-share button is not displayed correctly.

<img width="242" alt="スクリーンショット 2024-10-05 17 38 29" src="https://github.com/user-attachments/assets/b075faab-9375-4146-b196-4c7e39e11240">

The relevant code is on lines 13 and 393.
We need to modify the x-share button by referring to `README.md`, which is written in Japanese.

## Task list

- [ ] Compare `README.md` and `docs/README_EN.md`.
- [ ] Fix the X-share button.

## Others

**If you find another correction, please create an issue!
This way we can avoid multiple contributors making the same correction.**

For more information, check out the following
- #292 

---

If anyone would like to challenge this Issue, please add a comment!

Thank you for your interest in this issue 🚀.

**Comment by PAVAN507-STAR** [comment]
Hii @kazzyfrog.I would like to work on this issue.Can you assign me this issue?

**Comment by kazzyfrog** [comment]
Hii @PAVAN507-STAR.

Just now assigned!
If you need help, please add a comment!

Thank you ;)

**Comment by PAVAN507-STAR** [comment]
Hii  sir @kazzyfrog.Solved the issue and raised the PR

**Comment by kazzyfrog** [comment]
Thank you!
I just added a review comment ;)

**Comment by PAVAN507-STAR** [comment]
@kazzyfrog should i raise a pr again with suggested changes

**Comment by kazzyfrog** [comment]
Essentially, you can just add the change, within the same PR 👍
