### ISSUE TITLE
プルリクエストテンプレートの作成

### ISSUE THREAD

**Issue by pss-aileen** [first-contributions-ja/first-contributions-ja.github.io#3]
## プルリクエストテンプレートとは

> ”本番適用するソースコードは必ずレビューする” というルールを決めたとしても「忙しくてレビューできない」「レビューしたいけど、どこが変わったか見つけるのが面倒」などの意見が多く、レビューをしなくなっていきます。
> 
> コードレビューする文化を組織に根付かせることは、とても難しいです。しかし、プルリクエストを使うことで組織にコードレビューする文化を根付かせることができます。
> [プルリクエストとは？｜サル先生のGit入門【プロジェクト管理ツールBacklog】](https://backlog.com/ja/git-tutorial/pull-request/01/)

> **プルリクエストとは簡単に言うと、開発者のローカルリポジトリでの変更を他の開発者に通知する機能です。プルリクエストは次のような機能を提供します。**
> - 機能追加や改修など、作業内容をレビュー・マージ担当者やその他関係者に通知します。
> - ソースコードの変更箇所をわかりやすく表示します。
> - ソースコードに関するコミュニケーションの場を提供します。

- テンプレート例  ref: [GitHub pull request template](https://axolo.co/blog/p/part-3-github-pull-request-template)
  - チェックリストなどを含めるパターン
  - 詳細説明を書くパターン

<img src="https://github.com/first-contributions-ja/first-contributions-ja/assets/140990100/523e2f2d-c448-4984-b84d-ab82f7b90aa7" width="400">

- [リポジトリ用のプルリクエストテンプレートの作成 - GitHub Docs](https://docs.github.com/ja/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)
- [GithubでPull Request テンプレートを使用するには？ #Git - Qiita](https://qiita.com/atsutama/items/03753925762fd094ec9c#:~:text=Pull%20Request%E3%83%86%E3%83%B3%E3%83%97%E3%83%AC%E3%83%BC%E3%83%88%E3%81%AF%E3%80%81%E3%83%97%E3%83%AD%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88,%E3%83%95%E3%82%A3%E3%83%BC%E3%83%89%E3%83%90%E3%83%83%E3%82%AF%E3%82%92%E6%8F%90%E4%BE%9B%E3%81%A7%E3%81%8D%E3%81%BE%E3%81%99%E3%80%82)

**Comment by kagomen** [comment]
プルリクテンプレートの作成を、

- .github/docs/PULL_REQUEST_TEMPLATE/pull_request_template.md
- .github/docs/pull_request_template.md
- .github/pull_request_template.md

上記の3つのディレクトリを練習用リポジトリで試したのですが、3番目の.githubディレクトリに直接pull_request_template.mdファイルを作成した場合のみテンプレートが反映され、**その他の場合は反映されなかった**ので報告です。

というのも、以下の公式ドキュメントの文意が掴めなかったので、実際に試したみた次第です。
<img width="729" alt="スクリーンショット 2024-03-15 0 16 43" src="https://github.com/first-contributions-ja/first-contributions-ja.github.io/assets/154225199/2e5e053c-b6b3-4676-9616-d44e8e24d05d">
[リポジトリ用のプルリクエストテンプレートの作成 -GitHub Docs](https://docs.github.com/ja/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)

自分が間違えてるだけかなあと思ったのですが、[似たような方](https://zenn.dev/shootacean/articles/suspect-when-github-pr-template-is-not-reflected)もいらっしゃったので、一応報告してみました！

**Comment by kagomen** [comment]
参考になりそうな記事
[プルリクエストのテンプレートを改善したら、レビュー効率が上がった話](https://zenn.dev/stafes_blog/articles/d235146a37e0d5)

**Comment by kazzyfrog** [comment]
お二人ともありがとうございます！
やっていきます🔥

**Comment by kazzyfrog** [comment]
@kagomen 

> 自分が間違えてるだけかなあと思ったのですが、[似たような方](https://zenn.dev/shootacean/articles/suspect-when-github-pr-template-is-not-reflected)もいらっしゃったので、一応報告してみました！

これ参考になりました！ありがとうございます！
そして、 #43 でまさに今悩ましい問題に直面しています！
help wanted !!
