### ISSUE TITLE
コントリビューターが実際に変更を加えるデータファイルを作成する

### ISSUE THREAD

**Issue by kazzyfrog** [first-contributions-ja/first-contributions-ja.github.io#36]
## 概要

チュートリアルに沿って、コントリビューターが実際に変更を加えるファイルを作成します

## タスク一覧
+ [ ] rootにファイルを作成し、ダミーデータを記載しておく

## その他

下記に２点に関して、何かアイデアがあればコメントください：
- ファイル名は、data.jsonか、Contributors.jsonとか？で良いと思ってます
- データに関しては、初期は以下のような形で良いのではないかと思っていますが、好きな技術など内容は一旦適当です：
```json
[
  {
    "name": "kazzyfrog",
    "github": "https://github.com/kazzyfrog",
    "favoriteStack": "React",
    "text": "Hi there 👋 ."
  },
]
```

## 参考
- https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/src/Jsons/Contributors.json
- https://github.com/firstcontributions/first-contributions/blob/main/Contributors.md?plain=1
- https://github.com/Syknapse/Contribute-To-This-Project/blob/master/index.html

**Comment by pss-aileen** [comment]
> * ファイル名は、data.jsonか、Contributors.jsonとか？で良いと思ってます

contributors.json がわかりやすくて良いと思います！

> * データに関しては、初期は以下のような形で良いのではないかと思っていますが、好きな技術など内容は一旦適当です：

こちらもこれで良いかと思います！
