### ISSUE TITLE
【週報】2024/03/17

### ISSUE THREAD

**Issue by pss-aileen** [first-contributions-ja/first-contributions-ja.github.io#42]
## As Is
- 作業をする上で「これってどうしたらいいのかな？」がわからないことがある

## To Be
みんなで共有して、作業の不安をなくしたり、作業をスムーズにする

### 最新情報の確認の仕方 OK
- 「メンター必読最新のタスク」Issueを作る
  - 作ってみた #51
- 最新のタスクをTOPで提示、コメントにタスクの概要をまとめる
- 1つのプロジェクトが終わったらコメントをhide、TOPコメント書き換え、最新のタスクをコメントに追加
- 重要コメントや今後もみんなに共有すべき内容は別途まとめる
  - 作ってみた #52
- コードについては後にDocumentにまとめる
  - コーディング規約とかに。（issueをたてる）
  - まとめられたらhideで隠すなど

### 実装する上での注意点の共有の仕方（全体的なもの） 
  - #37 （↑の共有を使う）
  - **★週報** やる！！！！
    - やれたらキャッチアップしやすいかも
    - issue or discord...?、discussions
    - ターゲット: 初心者
      - readme見る
      - フォーク、プルリク系はreadmeだけ
    - より多くコントリビューションしたい人
      - contribution.md と issue を見る？と思う
      - issue..
        - 今すること、タスクが書いてある...！
        - ピン留めしたissue、現在やっていることがわかりやすい...！
        - discussions
          - 将来的なことを話す場所としたほうが良いかな？
          - 追加したい機能
          - コーディング規約（将来的に「こうしていったほうが良いよね？」的な話ができれば）
        - 問題
          - 暫定の情報の共通方法どうするか→Discussionでも良い？
          - キャッチアップできている人が、PRなどを見て訂正など?

↓

### **キャッチアップするために**
- 週報を書く！

### CONTRIBUTING.md の内容について確認 OK
- [CONTRIBUTING.md](https://github.com/first-contributions-ja/first-contributions-ja.github.io/blob/main/docs/CONTRIBUTING.md)
- GitHubの各機能の使い分け
- ブランチの命名規則
- プルリクエストのテンプレート
- コミットメッセージのテンプレート

### Issueの書き方、目的の共有 OK
- 書き方: とりあえず1つのテンプレートで新機能やバグ修正などを作成する
- 目的: 作業する理由やすべきこと明示するため

### Issueの粒度 OK
- 基本小さめでも大きめでもよし
  - 難しいなと思えば別でissue立てる
- `## 残課題`  から作成 [ref](https://github.com/first-contributions-ja/first-contributions-ja.github.io/issues/42#issuecomment-1998299158) でもOK

### プリリクエストの書き方、目的の共有 OK
- 書き方: プルリクエストのテンプレを使用
- 目的: 作業内容を理解、懸念点などを整理、レビューをしやすくするため

### プルリクエスト作成、コードレビュー、修正、承認、マージまでの流れ OK
- マージまでの流れ [GitHub における PR レビュープロセス](https://developer.mamezou-tech.com/blogs/2022/06/29/reviewing-pr-on-github/)、[ref](https://github.com/first-contributions-ja/first-contributions-ja.github.io/discussions/40#discussioncomment-8788309)
- 基本何人がレビューするか: 全員がレビューできるとは限らないので一人でも可能
- 一人がレビュー、承認、マージ: OK
- マージの仕方: 「merge」か「squash」[GitHub上のマージ方法について - GitHub Docs](https://docs.github.com/ja/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/about-merge-methods-on-github)
- **以下決定**
  - 1issueに対して1コミットが見やすいかも？
  - 以下のやり方でとりあえずなんとなくでもやれればOK
  - **コミット1つ**
    - 普通のマージ
    - `Merge pull request #49 from first-contributions-ja/fix/#45_delete_code_of_conduct` こういったものはあって良い！気にしなくて良い！
  - **コミット複数**
    - squash、タイトルをコミットメッセージに書き換える 

### 相談や報告方法、頻度 OK
- #39
- IssueやDiscussionsでの議論Welcome
- ただ、反応が早く来るとは限らないので、単独で決めてすすめ、PR出してみんなに確認してもらう方法がスムーズかも！
- [バージョン1リリースするまで「コードについて」](https://github.com/first-contributions-ja/first-contributions-ja.github.io/discussions/52#discussioncomment-8816902) こちらで暫定コーディングスタイルを書き込んで、勝手に作業する感じでやる
- それを見ながら各自すすめていく
- 日曜日のMTGのときに改めてコーディング規約について整理する
- 一人ひとりの判断を書き残す感じ

### Issue、Discussionのラベル OK
- #23
- 最新のタスク確認するためにあったほうが良いかと思った（&のちに遡りたい時用）
- 緊急度の高いものが認識できればいいと思ったが...
- とりあえずラベル整理してみた [label](https://github.com/first-contributions-ja/first-contributions-ja.github.io/labels)
- いったんはdocumentationとかfeatureとかbug、運営関連程度でよいかもと考えている

### 知見・知識の共有について OK
- プロジェクトに必要なものは #52
- 技術的なものに関しては暇と時間があれば好きに書き残す感じで！
- https://github.com/first-contributions-ja/first-contributions-ja.github.io/discussions/54
- ↑独り言のように投稿して解決策を見つけていくような流れでよい、メモ程度でもOK
- ただ、プロジェクトをすすめることが優先なので、あまり気にしなくても良い

## その他
- Discussionsだと迷子になりそうな気がしたのでissueにしました
- 上記以外に話した方が良いと思われる内容があればEditで追記してください！

## 参考
- 現状なし

**Comment by kazzyfrog** [comment]
Issueの粒度に関しては、PRテンプレに下記を追加したので、できなかったタスクを切り出す形でも良さそうです！

```
## 残課題
<!-- やれていないこと、または作業中に発見した別の問題についての簡潔な説明。
別対応となる場合は、新たにイシューを作り#2 の様に紐付けます。 -->
```

**Comment by pss-aileen** [comment]
### Discussions
- どんな、どれくらいの位置づけ
  - issue、コントリビュートmd は絶対みるけど
  - discussionsは必ずしも見なくて良い
  - issueから引用されていたらそのdiscussionsは見る
  - discussionsを見ないと進められない...といった風にはしたくない気持ちがある

**Comment by pss-aileen** [comment]
### Discussionsを閉じるか、閉じないか
- とりあえず閉じない方向で！！

**Comment by pss-aileen** [comment]
### 次にMTGで話したいことなどを週報にまとめる
- Discussionsでわいて、議論が必要なものを週報にはっておく

**Comment by pss-aileen** [comment]
## 次の一週間何をするか
- こまごましたdocumentの追加、修正をする
- その後、実装に入っていく
- TOPページ
- ABOUTページ

- githubのページが怖い
- その前にページとしてあれば安心するかもしれない
- 対象は初心者
  - どんな初心者？
    - GitHub触ったことがない、ぼんやりとしかわからない方
    - 英語に抵抗がある人

**Comment by pss-aileen** [comment]
## まとめ
概要まとめてkanaさんへ

**Comment by pss-aileen** [comment]
### レビューの仕方
- マージせずにも「これOK」というのもあり
- レビュー分かる範囲で良い
- とりあえず動いてる、コード的にもあまり問題がなさそうだったらレビューをOKする
- 自分の持ってる技術力で判断できればOK

**Comment by pss-aileen** [comment]
### コーディング規約や実装方針がうまく共有できていな時
- PRなどでその点を引用、リファレンス付きで共有
- 毎日とか頻繁にissueを見ればわかるかもしれない
- ただ、頻繁に見ない場合は共有事項が抜ける場合は絶対ある
- その場合はその都度、分かる人が分かる範囲で共有、議論できればOK！

**Comment by pss-aileen** [comment]
一応MTG終わったのとDiscussionsに移行する感じなのでclose
