### ISSUE TITLE
リポジトリ名を first-contributions-ja から first-contributions-ja.github.io に変更するか、しないか

### ISSUE THREAD

**Issue by pss-aileen** [first-contributions-ja/first-contributions-ja.github.io#5]
Discordより

> メモ：
> デフォルトだと、github pagesのURLは、<アカウント名>.github.io/リポジトリ名/なので、現在URLが、次のようになってます：
> https://first-contributions-ja.github.io/first-contributions-ja/
> 
> なので、リポジトリ名を、first-contributions-ja.github.ioにしてもいいかもです！
> そうしたら、URLが、https://first-contributions-ja.github.io になる：
> https://pages.github.com/

**Comment by pss-aileen** [comment]
個人的にはこちら変更で良いかと思います！

**Comment by kagomen** [comment]
同じく変更で良いと思います！

**Comment by kazzyfrog** [comment]
これは、リポジトリ名を変更する方向で行きたいと思います！
ただ、変更したらリモートリポジトリのURLも変わってしまって、ローカルからのpushなどに影響が出そうなので、作業の区切りが良さそうな後々でいいかもですね！

**Comment by pss-aileen** [comment]
プルリク #22  が終わったぐらいで変更でも良さそうな気がします！

**Comment by pss-aileen** [comment]
ふと思ったんですが、
今後私たち（Discordのメンバー）で他の共同プロジェクトを立ち上げていく場合は他の組織を作ってやっていく
といった流れになるのでしょうか？

ちゃんと調べられていないのですが...
[組織とチームに関するドキュメント - GitHub Docs](https://docs.github.com/ja/organizations)

あ、でも全く新しい人が参加したりするかもしれないから、新しい組織を作った方が良いですね。
このプロジェクトはこの組織、別のプロジェクトは別の組織でと....

**Comment by kazzyfrog** [comment]
リポジトリ名を変更しました！
リモートのURLが変わると思うので、合わせて変更お願いします！

**Comment by kazzyfrog** [comment]
Organizationに関しては、グループ名的なの作ろうかとも考えたのですが、とりあえず１回やってみる感じで、プロジェクトに対応した組織にしてみました。
次回以降は、１つのグループで色々作っていく形でも、同じようにプロジェクトごとにOrganization作る形でも、良さそうです！
