### ISSUE TITLE
【週報】2024/03/24 来週

### ISSUE THREAD

**Issue by pss-aileen** [first-contributions-ja/first-contributions-ja.github.io#55]
- 1コメントにつき1トピック
- MTG時に話したこと、決まったことをを1コメントの中にまとめる

なにか話したい内容があればコメントに書いておいてください！

**Comment by pss-aileen** [comment]
## サンプルトピック
- これがわからない
- これをどう考えればよいかわからない

---

## 結論
- Aという方針でいくことになった

**Comment by kagomen** [comment]
たしかに、イシューテンプレートに週報のテンプレートを追加しても良さそうですね！！

**Comment by pss-aileen** [comment]
> たしかに、イシューテンプレートに週報のテンプレートを追加しても良さそうですね！！

ですね！
と考えているうちにDiscussionsでpinどめできることを知り
こちらでまとめるか悩み始めました...！

**Comment by pss-aileen** [comment]
Discussionsでまとめた方が良い気がしているのでclose。
