### ISSUE TITLE
必要なディレクトリ・ファイルを作成する

### ISSUE THREAD

**Issue by pss-aileen** [first-contributions-ja/first-contributions-ja.github.io#61]
## As Is

- #57 
- ディレクトリが決まっていない

## To Be

- ディレクトリを確定させる
- フォルダ、ページを作る

## Action

- [x] 以下のツリーにそって作成

```
src/
├─app
|   ├─page.tsx
|   ├─layout.tsx
|   ├─loading.tsx
|   └─not-found.tsx
|
├─components
|   ├─header.tsx
|   ├─footer.tsx
|   └─ui
|     └─button.tsx
```

## その他

- #60 にて一人でコンポーネントの考え方、ディレクトリについて考えております...！
- まとまりましたらこちらのissueにて共有、相談いたします！→まとまった！Actionsに記載！

**Comment by kagomen** [comment]
調査ありがとうございます🌟

> そのページ独自のテキストや繰り返さないものはコンポーネントにしなくても良い

たしかにその通りだなーと思いました👀

> 上記の通り進めても良いでしょうか？

大丈夫です！
