### ISSUE TITLE
各自でTailwind CSSを書いていくので、Webページが大体完成したらCSSの整理を行う

### ISSUE THREAD

**Issue by pss-aileen** [first-contributions-ja/first-contributions-ja.github.io#62]
## As Is

- 実装方針がデザイン還付通りに表示させることを目標とすることが決まった
- CSSをどう書くか、どうまとめるかといたことが決まっていない
- これら↓がざっくり出来上がったあとに着手
- #32 
- #33 
- #56 

## To Be

- 全員でCSSの書き方を共有、ある程度ルール制定する
- 決まったことをベースにCSSを変更する

## Action

- [ ] CSSの理想の書き方を共有 #59 
- [ ] ベストな書き方を決める
- [ ] それに沿ってスタイルに関する設定を変更する
- [ ] コーディング規約的なものを作る場合は別issueで書く

## その他

- 全体的に進んできたらまた議論で

## 参考
- #57

**Comment by kagomen** [comment]
こちらのイシュー気づかずにDiscussionsに[Tailwindのあれこれについて #59](https://github.com/first-contributions-ja/first-contributions-ja.github.io/discussions/59)を立ててしまいました……！
こちらに移動して議論する方が良いですかね❔

**Comment by pss-aileen** [comment]
> こちらのイシュー気づかずにDiscussionsに[Tailwindのあれこれについて #59](https://github.com/first-contributions-ja/first-contributions-ja.github.io/discussions/59)を立ててしまいました……！

#59 ですすめていただいて大丈夫です！
こっちにはおおよそ決まった内容などを書いたり、#59 をリファレンスとして使えば良いかと思うので！

TOPコメントのActionのところにリンクつけておきました！

**Comment by pss-aileen** [comment]
一旦close
また何かあれば開くか、新しくissueたてる
お好きに！
