### ISSUE TITLE
レスポンシブ対応する

### ISSUE THREAD

**Issue by pss-aileen** [first-contributions-ja/first-contributions-ja.github.io#64]
## As Is

- 現状PC版のみの実装

## To Be

- レスポンシブ対応する
  - SPだけでもいいけど、タブレットサイズもいければ

## Action

- [ ] ブレイクポイント決める→[Responsive Design - Tailwind CSS](https://tailwindcss.com/docs/responsive-design)これの中のどれかで良いか。
- [ ] TailwindCSSでの効率的な実装方法を探す
- [ ] 実装

## その他

- PC版の実装が終わったら考える

**Comment by kagomen** [comment]
@pss-aileen
こちらのタスク、ロゴ画像が完成してから取り組んだ方が良いでしょうか？👀
ヒーローページの現在の画像に差し替える画像が同じ大きさくらいだったらタスクに取り掛かっても良いかなと思ったのですが、どんなもんでしょうか❓

**Comment by kagomen** [comment]
スマホ
![localhost_3000_(iPhone SE) ](https://github.com/first-contributions-ja/first-contributions-ja.github.io/assets/154225199/32b56d27-554f-456f-962b-71767a1d081d)

タブレット
![localhost_3000_(iPad Air)](https://github.com/first-contributions-ja/first-contributions-ja.github.io/assets/154225199/a55bc0b4-268a-4f98-a7c5-cabc92aa8cb8)

PC
![screencapture-localhost-3000-2024-03-27-18_31_44](https://github.com/first-contributions-ja/first-contributions-ja.github.io/assets/154225199/bd0d17ed-d2db-4e02-a2d6-70263f79edfe)

**Comment by kagomen** [comment]
## 大きな変更点

- 「1234人参加中」を下にした
- スマホ版アバウトセクションの赤枠をなくした
  - 画面が窮屈に感じたため
- 背景色を薄いグレーに変更
  - アバウトセクションの赤枠をなくすと画面が寂しく感じたため
- リストの番号部分の変更
  - 少しでも画面を派手にするため
- オクトキャットの追加
  - 理由は同上。規約的に利用OKかと思いますが、気になる場合は他のフリー画像でも！
- 文章を明るくした
  - 理由は同上
