### ISSUE TITLE
週報用のテンプレートを作成する

### ISSUE THREAD

**Issue by kagomen** [first-contributions-ja/first-contributions-ja.github.io#75]
## 概要
週報用のテンプレートを作成する

## タスク一覧

- [x] IssueかDiscussionか決める
- [ ] どんな項目が必要か調査
- [ ] テンプレート作成

**Comment by kagomen** [comment]
## トピック

## MTGログ

## 結論

*** 
参考 #55

**Comment by kagomen** [comment]
現在の週報の書き方が、

- 次のMTGで話したいことを書いておく
- MTGしながら書記係が話した内容をメモしていく
- **まとめ** でまとめる

なので、テンプレート必要なのか……？という気もしてきた
また、現在の書き方はとても理にかなっていると思う！

**Comment by pss-aileen** [comment]
週報なのですが、
議論したい話題が多数あった場合、
コメントにトピックを残し、
それに対してリプライをつけられるのでMTGのログがつけやすく
Discussionsで良いかなと思い始めました。

以下来週分を仮で作ってみました。

#76 

テンプレートですが、
議論用のテンプレートをコピーするためのテンプレートを用意しておくのは良いかな？と思います。

![スクリーンショット 2024-03-20 1 06 02](https://github.com/first-contributions-ja/first-contributions-ja.github.io/assets/140990100/70025aed-63a9-41fc-b8ef-6f74ea024cb7)

ソースコードにするとワンクリックで内容をコピーできるので！😎✨

ただちょっと試作段階なので、
今週末この↑テンプレートを使ってみて内容を確定させたいかな！と思っています！

**Comment by pss-aileen** [comment]
色々と変化がありそうなので一旦Close
必要であればreopenで！
issue立てありがとうございました🙌
