### ISSUE TITLE
README.mdの作成

### ISSUE THREAD

**Issue by pss-aileen** [first-contributions-ja/first-contributions-ja.github.io#8]
- 最終的にはチュートリアルの内容を記述？

**Comment by kazzyfrog** [comment]
よかったら自分このタスクやりますよ！
ドキュメントなので、それっぽいの１回作ってから、適宜更新していければと思います！

１つ悩むのは、チュートリアルの内容を記載する場合、CONTRIBUTING.mdの[基本的な開発方法](https://github.com/first-contributions-ja/first-contributions-ja.github.io/blob/main/docs/CONTRIBUTING.md#基本的な開発方法)と、重複する形になるので、
どっちかに記載して、もう片方はリンクを飛ばす形の方が良いですかね？

**Comment by kazzyfrog** [comment]
個人的には、以下のように分けるといいのかな、と思ってます：
- README.mdに、チュートリアルの内容を記載
- CONTRIBUTING.mdで、チュートリアル以外のイシュー・バグ報告などの、より多くの貢献をしたい人やメンテナー向けのガイドを作成

よろしければ、合わせてCONTRIBUTING.mdからの「基本的な開発方法」段落の移行もやりますよ！

**Comment by kagomen** [comment]
> - README.mdに、チュートリアルの内容を記載
> - CONTRIBUTING.mdで、チュートリアル以外のイシュー・バグ報告などの、より多くの貢献をしたい人やメンテナー向けのガイドを記載

良いと思います！
ありがとうございます🙏

**Comment by pss-aileen** [comment]
> よかったら自分このタスクやりますよ！

ありがとうございます！

質問なのですが、メンター（私たち）とdata.jsonを追加する人（OSS練習する方）とで、少し手順が違う？と思ったのですが、README.mdのチュートリアルに全てまとめる感じでしょうか？

私が思うのは

- README.md: チュートリアルの内容
- CONTRIBUTING.md: チュートリアル以外のイシュー・バグ報告などの、より多くの貢献をしたい人やメンテナー向けのガイドを記載 + **チュートリアルに似てるけど、メンテナー向けの貢献方法（クローンとかプルリクとか）**

ガイドというのが、**メンテナー向けの貢献方法（クローンとかプルリクとか）** を含んでいる前提であれば問題ないです🙆‍♀️

**Comment by kazzyfrog** [comment]
> メンテナー向けの貢献方法（クローンとかプルリクとか）
確かに、少し手順が違う部分がありますね
イシューベースなので、コメントしてアサインされてから着手するとかもそうですよね！

これは、README.mdとCONTRIBUTING.mdをまとめて色々書いていくブランチ切って、
ディスカッションしながら、複数人で細かくコミットして、最後にsquash margeでまとめてもいいかもですね！

一旦、自分がREADME.mdの大枠作ります！

**Comment by pss-aileen** [comment]
> PR上でディスカッションしながら

そのような進め方もあるのですね！！
承知しました！

ではREADME.md大枠よろしく願いいたします🙇
