### ISSUE TITLE
Tailwind CSSのclassNameの並びを整えるためにprettier-plugin-tailwindcssを導入する

### ISSUE THREAD

**Issue by pss-aileen** [first-contributions-ja/first-contributions-ja.github.io#88]
## 概要
- TailwindCSSの記述順がばらばらになるのでそれを規則にそって並べ替える
- [tailwindlabs/prettier-plugin-tailwindcss](https://github.com/tailwindlabs/prettier-plugin-tailwindcss) を導入する

## タスク一覧

- [ ] prettier-plugin-tailwindcssをインストールする
- [ ] 設定をファイルに適応させる

## その他

- https://github.com/first-contributions-ja/first-contributions-ja.github.io/discussions/69#discussioncomment-8849513

**Comment by kazzyfrog** [comment]
これも、あまりそうなのでやっていく！
