### ISSUE TITLE
運営にあたっての基盤作り

### ISSUE THREAD

**Issue by pss-aileen** [first-contributions-ja/first-contributions-ja.github.io#9]
管理のプロジェクト: https://github.com/orgs/first-contributions-ja/projects/1

- [x] #4
- [x] #6
- [x] #1 
- [x] #2 
- [x] #3 

---

新しいお知らせ、みんなに共有したい内容はここに書き足して掲示板？みたいにしたらいいのかな？

- 全てのお知らせ、マネジメントについて書いていくissue
  - 今はこのタスク、次はこのタスクをしますよ〜とか？
- 最新のタスク（プロジェクト）用をお知らせするissue
  - 最新のプロジェクトにまつわるお知らせはこちらに書く 

この二つを常に開いておいて、まずここを見れば最新情報がわかる的な

**Comment by pss-aileen** [comment]
### このリポジトリ・プロジェクトの目標、作成目的

- 共同プロジェクトを体験してみる
- GitHubの使い方を学ぶ
- オープンソースの作法を学ぶ

### できること・挑戦
- GitHubを使い倒す
- 色々な機能の使い方を学ぶ
- コミット、プルリクエストを色々間違えてみてそこから対処を学ぶ
- issueやdiscussionにログをたくさん残して後で見る人にとっても学びとなるようなものにする

### 思うこと
- ここでたくさん試行錯誤して、誰かの参考になるようなリポジトリになれたらいいなと思った

**Comment by kazzyfrog** [comment]
> 取り組んだこと、学んだことをそれぞれまとめる場があれば良いなと思った....

これはまさに自分も思いました！

**Comment by kagomen** [comment]
なんか上に表示されてると思ったら……！
ピン留めできるんですね👀

**Comment by pss-aileen** [comment]
とりあえず終わったのでclose
