### ISSUE TITLE
ファビコンやOG画像、Twitterカードの画像の設定

### ISSUE THREAD

**Issue by kagomen** [first-contributions-ja/first-contributions-ja.github.io#94]
## 概要
ファビコンやOG画像、Twitterカードの画像を設定する

## タスク一覧

- [x] （画像が完成したら）画像データを配置する
- [ ] 画像データをフォルダにまとめることは可能か？（未調査）
- [x] OGP画像のリポジトリ Settings の Social preview へのアップロード
- [x] サイトの OGP画像の設定
- [x] サイトのファビコンの設定
- [ ] `page.tsx`のロゴ画像の入れ替え→ #64
- [ ] ディレクトリの整理 → #130 
- [x]  OGP画像をREADMEの上部に載せる

## その他

https://nextjs.org/docs/app/api-reference/file-conventions/metadata/app-icons
https://nextjs.org/docs/app/api-reference/file-conventions/metadata/opengraph-image

**Comment by kazzyfrog** [comment]
作成したロゴの、READMEの上部への記載、リポジトリ Settings の Social preview へのアップロードも、まとめてもいいかもです！

**Comment by pss-aileen** [comment]
> * OGP画像のリポジトリ Settings の Social preview へのアップロード

こちら重複issueがあったのと作業簡単だったのでしてしまいました！
