### ISSUE TITLE
Discussions に案内とチュートリアルに関する掲示板を掲載する

### ISSUE THREAD

**Issue by kazzyfrog** [first-contributions-ja/first-contributions-ja.github.io#98]
## 概要
#96 より
CONTRIBUTING.md に記載していた、Discussionsの内容を更新し、Discussionsの中に「ようこそ」的な案内を掲載する。
Discussionsを訪れた人にとって分かりやすく、更新もしやすくするため。

加えて、チュートリアルの質問用スレッドと、感想用スレッドの２つを用意する。

## タスク一覧

- [x] Discussions内に、案内（使い方やカテゴリなどのガイド）を記載する
- [x] チュートリアルの質問用スレッドと、感想用スレッドの２つを用意する

**Comment by pss-aileen** [comment]
さっくりやります！

**Comment by pss-aileen** [comment]
## カテゴリー設定

![スクリーンショット 2024-03-24 13 45 53](https://github.com/first-contributions-ja/first-contributions-ja.github.io/assets/140990100/ebe92e12-ce2a-4a6b-a602-536251268e8d)

https://github.com/first-contributions-ja/first-contributions-ja.github.io/discussions/categories

![スクリーンショット 2024-03-24 13 45 31](https://github.com/first-contributions-ja/first-contributions-ja.github.io/assets/140990100/9e1b152c-baec-4f80-adbf-9a1664aff2c7)

**Comment by pss-aileen** [comment]
## 【📣全員必読】first-contributions-ja へようこそ！

さっくりまとめてみました。
ご確認、ご意見等よろしくお願いします！

#101

**Comment by pss-aileen** [comment]
@kazzyfrog @kagomen

**Comment by kazzyfrog** [comment]
ありがとうございます！
しっかり整理されていて、見やすいと思います！！👍

１点だけご確認ください：
「メンター」という記載は「メンテナー」で統一した方がいいかも？と思いました！

**Comment by pss-aileen** [comment]
> 「メンター」という記載は「メンテナー」で統一した方がいいかも？と思いました！

ですね！メンテナーに変更しました！
このDiscussions以外にもメンターってどこかで書いていたような気がするので、見つけ次第メンテナーにしていきます！

**Comment by pss-aileen** [comment]
作成したので一旦Close
